sonar.organization=xsovad06
sonar.projectKey=xsovad06_sova
sonar.projectName=SOVA

sonar.sources=sova/
sonar.tests=tests/

sonar.python.version=3.12

sonar.exclusions=\
  **/templates/*.html,\
  **/static/**,\
  **/__pycache__/**,\
  **/migrations/**,\
  **/alembic.ini,\
  **/*.sh

sonar.test.inclusions=tests/**/*.py

sonar.python.coverage.reportPaths=coverage.xml

sonar.sourceEncoding=UTF-8
