"""Dashboard API routers: one router per resource/domain."""

__all__ = [
    "agents",
    "control",
    "costs",
    "dependencies",
    "feed",
    "fleet_insights",
    "fleet_manager",
    "handoff",
    "lifecycle",
    "logs",
    "mcp",
    "memory",
    "oversight",
    "overview",
    "prs",
    "queue",
    "quota",
    "resources",
    "roles",
    "runs",
    "server",
    "settings",
    "setup",
    "spec",
    "supervisor",
    "tasks",
    "telemetry",
    "work",
]
